version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_bff
    ports:
      - 3306:3306 
    volumes:
      - .docker/dbdata:/var/lib/mysql
